@echo off
echo Deteniendo procesos de Node.js...
taskkill /IM node.exe /F
echo Limpiando cache...
rmdir /s /q .next
echo Instalando dependencias...
npm install
echo Iniciando servidor en modo desarrollo...
npm run dev 